#!/usr/bin/env bash

# To enable this hook, add the .githooks directory to your git config's core.hooksPath
# Run: git config core.hooksPath .githooks

set -euo pipefail

# Get the root directory of the Git repository
REPO_ROOT=$(git rev-parse --show-toplevel)

# Function to clean up the temporary file on exit
# cleanup() {
#     rm -f "$tmp_sorted_file"
# }
# trap cleanup EXIT

main() {
   echo "Do something"
}

# main

