"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 30

format = '''
[┌─\[](green)$directory\] $custom$fill $all
[└─$os ](green)'''

# Custom
[custom.jj]
command = "prompt"
format = "$output"
ignore_timeout = true
shell = ["starship-jj", "--ignore-working-copy", "starship"]
use_stdin = false
when = true


# Customization
[directory]
read_only = " 󰌾"
format = '[$path](green)[$read_only](red)'
truncation_length = 5
truncation_symbol = '.../'
truncate_to_repo = false

[fill]
symbol = ' '

[os]
format = "[$symbol](green)"
disabled = false

[vcs]
disabled = true
order = ["jujutsu", "git"]

[git_branch]
disabled = true
symbol = " "
format = "$symbol$branch "

[git_commit]
disabled = true
tag_symbol = '  '

[git_status]
disabled = true
format = "([$all_status$ahead_behind]($style) )"
ahead = ' ${count}'
diverged = '󱪕  ${ahead_count} ${behind_count}'
behind = ' ${count}'
conflicted = '[](orange) '
up_to_date = ''
untracked = '[](blue) '
stashed = '[](blue) '
modified = '[󱇧](yellow) '
staged = '[$count󰸩 ](green)'
renamed = ' '
deleted = '🗑 '

# Disabled
[character]
disabled = true

[line_break]
disabled = true

[kubernetes]
disabled = false

# Nerd Font Symbols
[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = "󰎙 "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "🦀 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
